[profile.release]
debug = true

[profile.production]
inherits = "release"
lto = true

[workspace]
members = ["wasmtime-jni", "wasmtime-jni-exports", "tests/math", "tests/math-wit", "tests/slices", "tests/strings"]